# Generated by Django 3.2.6 on 2022-04-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='email',
            field=models.CharField(max_length=35),
        ),
    ]
