# Generated by Django 3.2.6 on 2022-05-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wed', '0003_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bhuvana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bhuvana', models.FileField(blank=True, null=True, upload_to='media/bhuvana/')),
            ],
        ),
        migrations.CreateModel(
            name='Rajesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rajesh', models.FileField(blank=True, null=True, upload_to='media/rajesh/')),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='file',
        ),
        migrations.AddField(
            model_name='song',
            name='song',
            field=models.FileField(blank=True, null=True, upload_to='media/song/'),
        ),
    ]
